[package]
name = "bridge-hub-rococo-integration-tests"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Bridge Hub Rococo runtime integration tests with xcm-emulator"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }

# Substrate
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sp-weights = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
pallet-assets = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }

# Polkadot
polkadot-core-primitives = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "rockmint-10005" }
polkadot-parachain = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "rockmint-10005" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "rockmint-10005" }
polkadot-runtime = { git = "https://github.com/paritytech/polkadot", branch = "rockmint-10005" }
xcm = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "rockmint-10005" }
xcm-executor = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "rockmint-10005" }
pallet-xcm = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "rockmint-10005" }

# Cumulus
parachains-common = { path = "../../../../common" }
cumulus-pallet-xcmp-queue = { default-features = false, path = "../../../../../pallets/xcmp-queue" }
cumulus-pallet-parachain-system = { path = "../../../../../pallets/parachain-system" }
pallet-bridge-messages = { default-features = false, path = "../../../../../bridges/modules/messages" }
bp-messages = { default-features = false, path = "../../../../../bridges/primitives/messages" }

# Local
xcm-emulator = { default-features = false, path = "../../../../../xcm/xcm-emulator" }
integration-tests-common = { default-features = false, path = "../../common" }
