[package]
authors = ["Parity Technologies <admin@parity.io>"]
name = "cumulus-relay-chain-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
polkadot-overseer = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "master" }

cumulus-primitives-core = { path = "../../primitives/core" }

sp-api = { git = "https://github.com/paritytech/substrate", branch = "oty-mp-queue" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "oty-mp-queue" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "oty-mp-queue" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "oty-mp-queue" }

tokio = { version = "1.24.2", features = ["sync"] }
futures = "0.3.25"
async-trait = "0.1.63"
thiserror = "1.0.38"
jsonrpsee-core = "0.16.2"
parity-scale-codec = "3.2.1"
