[package]
name = "integration-tests-common"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Common resources for integration testing with xcm-emulator"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }

# Substrate
grandpa = { package = "sc-consensus-grandpa", git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
sp-authority-discovery = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
sp-weights = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
sp-consensus-babe = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
pallet-assets = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
pallet-staking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }
pallet-im-online = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "asset-hub-westend-9435" }

# Polkadot
polkadot-core-primitives = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
polkadot-parachain = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
polkadot-service = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
polkadot-primitives = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
polkadot-runtime = { git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
polkadot-runtime-constants = { git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
kusama-runtime = { git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
kusama-runtime-constants = { git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
westend-runtime = { git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" } 
westend-runtime-constants = { git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
xcm = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
xcm-executor = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }
pallet-xcm = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "asset-hub-westend-9435" }

# Cumulus
parachains-common = { path = "../../../common" }
parachain-info = { path = "../../../pallets/parachain-info" }
cumulus-primitives-core = { path = "../../../../primitives/core" }
penpal-runtime = { path = "../../../runtimes/testing/penpal" }
asset-hub-polkadot-runtime = { path = "../../../runtimes/assets/asset-hub-polkadot" }
asset-hub-kusama-runtime = { path = "../../../runtimes/assets/asset-hub-kusama" }
asset-hub-westend-runtime = { path = "../../../runtimes/assets/asset-hub-westend" }
collectives-polkadot-runtime = { path = "../../../runtimes/collectives/collectives-polkadot" }
bridge-hub-kusama-runtime = { path = "../../../runtimes/bridge-hubs/bridge-hub-kusama" }
bridge-hub-polkadot-runtime = { path = "../../../runtimes/bridge-hubs/bridge-hub-polkadot" }
xcm-emulator = { default-features = false, path = "../../../../xcm/xcm-emulator" }

[features]
runtime-benchmarks = [
	"kusama-runtime/runtime-benchmarks",
	"polkadot-runtime/runtime-benchmarks",
	"westend-runtime/runtime-benchmarks",
]
