[package]
name = "cumulus-client-consensus-common"
description = "Cumulus specific common consensus implementations"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
async-trait = "0.1.73"
codec = { package = "parity-scale-codec", version = "3.0.0", features = [ "derive" ] }
dyn-clone = "1.0.12"
futures = "0.3.28"
log = "0.4.20"
tracing = "0.1.37"

# Substrate
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sp-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }

# Polkadot
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rockmint-10005" }

# Cumulus
cumulus-primitives-core = { path = "../../../primitives/core" }
cumulus-relay-chain-interface = { path = "../../relay-chain-interface" }
cumulus-client-pov-recovery = { path = "../../pov-recovery" }
schnellru = "0.2.1"

[dev-dependencies]
futures-timer = "3.0.2"

# Substrate
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "rockmint-10005" }

# Cumulus
cumulus-test-client = { path = "../../../test/client" }
cumulus-test-relay-sproof-builder = { path = "../../../test/relay-sproof-builder" }
